#include "test.h"
#include "ui/settings.h"
#include "render/camera.h"
#include "render/lighting.h"
#include "render/atmosphere.h"
#include <string.h>

// The game's options (src/ui/settings.c): the table, the menu built from it,
// the typed values and the change tracking (ROADMAP_v2 S8, D10, D27).

static Menu menu;

static void fresh(void) {
    menu_init(&menu, "Test");
    settings_init(&menu);
}

// Every option's choices and values line up, and the tabs are in menu order
// (the Controls rows are generated by settings_init)
static void test_table(void) {
    fresh();
    int last_tab = 0;
    for (int id = 0; id < SETTING_COUNT; id++) {
        const SettingDef *d = settings_def((SettingId)id);
        CHECK(d->label != NULL && d->label[0] != '\0');
        CHECK(d->choices != NULL);
        CHECK(d->count >= 1 && d->count <= MENU_MAX_OPTIONS);
        CHECK(d->default_choice >= 0 && d->default_choice < d->count);
        for (int c = 0; c < d->count; c++)
            CHECK(d->choices[c] != NULL && d->choices[c][0] != '\0');
        if (d->type == SETTING_TYPE_ACTION) {
            CHECK(d->values == NULL && d->count == 2 && d->default_choice == 0);
        } else {
            CHECK(d->values != NULL);
            CHECK(d->value_count == d->count);          // one value per choice
        }
        CHECK(d->tab >= last_tab && d->tab < SETTINGS_TAB_COUNT);   // grouped by tab
        last_tab = d->tab;
    }
    CHECK(settings_def(SETTING_BINDING_FIRST)->tab == SETTINGS_TAB_CONTROLS);
}

// settings_init builds the five tabs from the table
static void test_menu_built(void) {
    fresh();
    CHECK(menu.tab_count == SETTINGS_TAB_COUNT);
    int item_in_tab[SETTINGS_TAB_COUNT] = {0};
    for (int id = 0; id < SETTING_COUNT; id++) {
        const SettingDef *d = settings_def((SettingId)id);
        const MenuItem *it = &menu.tabs[d->tab].items[item_in_tab[d->tab]++];
        CHECK(strcmp(it->label, d->label) == 0);
        CHECK(it->option_count == d->count);
        CHECK(it->selected == d->default_choice);
        CHECK(it->options[d->count - 1] == d->choices[d->count - 1]);
    }
    for (int t = 0; t < SETTINGS_TAB_COUNT; t++) {
        CHECK(strcmp(menu.tabs[t].label, settings_tab_labels[t]) == 0);
        CHECK(menu.tabs[t].item_count == item_in_tab[t]);
    }
    // The Menu Sweep skips these by label (src/debug/testbed.c)
    CHECK(strcmp(menu.tabs[SETTINGS_TAB_CONTROLS].label, "Controls") == 0);
    CHECK(strcmp(settings_def(SETTING_RESET_SCENE)->label, "Reset Scene") == 0);

    // Controls: one option per remappable demo action, named and defaulted by
    // demo_controls.c; the choices are the bindable buttons, Start not among them
    CHECK(menu.tabs[SETTINGS_TAB_CONTROLS].item_count == DEMO_REMAP_COUNT);
    for (int a = DEMO_REMAP_FIRST; a < DEMO_REMAP_FIRST + DEMO_REMAP_COUNT; a++) {
        const SettingDef *d = settings_def(SETTING_BINDING(a));
        CHECK(strcmp(d->label, demo_action_names[a - ACTION_GAME_FIRST]) == 0);
        CHECK(settings_int(SETTING_BINDING(a)) == demo_default_button((ActionId)a));
    }
    const SettingDef *c0 = settings_def(SETTING_BINDING(DEMO_REMAP_FIRST));
    for (int c = 0; c < c0->count; c++) {
        int btn = ((const int *)c0->values)[c];
        CHECK(strcmp(c0->choices[c], pad_button_name((PadButton)btn)) == 0);
        CHECK(btn != BTN_START);
    }
}

// The typed accessors return the value of the selected choice
static void test_values(void) {
    fresh();
    CHECK(settings_bool(SETTING_DEBUG_TEXT) == true);          // "On" is choice 0
    CHECK(settings_bool(SETTING_SOUND) == false);              // default Off
    CHECK(settings_int(SETTING_FRAME_RATE) == 0);              // 60: the display's rate
    CHECK(settings_int(SETTING_ATMOSPHERE) == -1);             // Custom
    CHECK(settings_int(SETTING_CAMERA_MODE) == CAMERA_MODE_ORBITAL);
    CHECK(settings_int(SETTING_LATENCY) == LATENCY_LOW);
    CHECK(settings_bool(SETTING_RUMBLE));
    CHECK_NEAR(settings_float(SETTING_SFX_VOLUME), 0.8, 1e-6);
    CHECK_NEAR(settings_float(SETTING_AMBIENT), 0.20, 1e-6);    // D27: the menu's 20 %
    CHECK_NEAR(settings_float(SETTING_POINT_RADIUS), 300.0, 1e-6);
    color_t bg = settings_color(SETTING_BG_COLOR);
    CHECK(bg.r == 0x60 && bg.g == 0x80 && bg.b == 0xD0 && bg.a == 0xFF);   // Light Blue
    CHECK(strcmp(settings_choice_name(SETTING_BG_COLOR), "Light Blue") == 0);

    settings_set_choice(SETTING_SUN_DIR, 3);                   // Sunset
    const float *dir = settings_vec3(SETTING_SUN_DIR);
    CHECK_NEAR(dir[0], 0.866, 1e-6);
    CHECK_NEAR(dir[1], 0.200, 1e-6);
    CHECK_NEAR(dir[2], 0.458, 1e-6);
    settings_set_choice(SETTING_ATMOSPHERE, 5);
    CHECK(settings_int(SETTING_ATMOSPHERE) == ATMOSPHERE_SUNSET);
    settings_set_choice(SETTING_SHADOWS, 2);
    CHECK(settings_int(SETTING_SHADOWS) == SHADOW_PROJECTED);
    settings_set_choice(SETTING_SHADOWS, 7);                   // out of range: ignored
    CHECK(settings_int(SETTING_SHADOWS) == SHADOW_PROJECTED);

    settings_step_choice(SETTING_CAMERA_MODE, -1);             // wraps: Orbital -> Follow
    CHECK(settings_int(SETTING_CAMERA_MODE) == CAMERA_MODE_FOLLOW);
    settings_step_choice(SETTING_CAMERA_MODE, 1);
    CHECK(settings_int(SETTING_CAMERA_MODE) == CAMERA_MODE_ORBITAL);

    settings_set_bool(SETTING_SOUND, true);                    // finds "On" (choice 0)
    CHECK(settings_choice(SETTING_SOUND) == 0 && settings_bool(SETTING_SOUND));
    settings_set_bool(SETTING_FOG, true);                      // finds "On" (choice 1)
    CHECK(settings_choice(SETTING_FOG) == 1);

    settings_set_disabled(SETTING_FOG_NEAR, true);
    CHECK(menu.tabs[SETTINGS_TAB_ENVIRON].items[2].disabled);
    settings_set_disabled(SETTING_FOG_NEAR, false);
    CHECK(!menu.tabs[SETTINGS_TAB_ENVIRON].items[2].disabled);
}

// An action option fires once and puts itself back
static void test_trigger(void) {
    fresh();
    CHECK(!settings_trigger(SETTING_RESET_SCENE));
    settings_set_choice(SETTING_RESET_SCENE, 1);               // "Reset!"
    CHECK(settings_trigger(SETTING_RESET_SCENE));
    CHECK(settings_choice(SETTING_RESET_SCENE) == 0);
    CHECK(!settings_trigger(SETTING_RESET_SCENE));
}

// Change tracking: everything counts as changed after init and after
// settings_invalidate (D27); a take is per option; Cancel's revert counts
static void test_changes(void) {
    fresh();
    for (int id = 0; id < SETTING_COUNT; id++)
        CHECK(settings_take((SettingId)id));
    for (int id = 0; id < SETTING_COUNT; id++)
        CHECK(!settings_take((SettingId)id));

    settings_set_choice(SETTING_BRIGHTNESS, 0);
    CHECK(settings_take_range(SETTING_SUN_DIR, SETTING_SHADOW_DARKNESS));
    CHECK(!settings_take(SETTING_BRIGHTNESS));                 // the range took it
    CHECK(!settings_take_range(SETTING_SUN_DIR, SETTING_SHADOW_DARKNESS));

    settings_set_choice(SETTING_SUN_DIR, 1);                   // first of the range...
    settings_set_choice(SETTING_SHADOW_DARKNESS, 0);           // ...and last: both taken
    CHECK(settings_take_range(SETTING_SUN_DIR, SETTING_SHADOW_DARKNESS));
    CHECK(!settings_take(SETTING_SHADOW_DARKNESS));

    settings_set_choice(SETTING_FOG_COLOR, 1);                 // back and forth between
    settings_set_choice(SETTING_FOG_COLOR, 0);                 // takes: not a change
    CHECK(!settings_take(SETTING_FOG_COLOR));

    settings_invalidate();
    CHECK(settings_take(SETTING_FOG_COLOR) &&
          settings_take(SETTING_BINDING(DEMO_REMAP_FIRST + DEMO_REMAP_COUNT - 1)));

    // The menu edits the live value; Cancel puts the old one back, which
    // counts as a change again (the demo re-applies it)
    settings_take_range(SETTING_BG_COLOR, (SettingId)(SETTING_COUNT - 1));
    menu_open(&menu);
    menu.active_tab = SETTINGS_TAB_LIGHTING;
    menu.tabs[SETTINGS_TAB_LIGHTING].cursor = 0;               // Sun Dir
    menu_change_value(&menu, 1);
    CHECK(settings_take(SETTING_SUN_DIR));
    menu_close(&menu, false);
    CHECK(settings_take(SETTING_SUN_DIR));
    CHECK(!settings_take(SETTING_SUN_DIR));
}

void run_settings_tests(void) {
    RUN_TEST(test_table);
    RUN_TEST(test_menu_built);
    RUN_TEST(test_values);
    RUN_TEST(test_trigger);
    RUN_TEST(test_changes);
}
